name: v2 Test @ Go 1.11

on:
  pull_request:
    branches:
      master

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go 1.11
          uses: actions/setup-go@v1
          with:
            go-version: 1.11

      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          go get github.com/urfave/gfmrun/cmd/gfmrun
          go get golang.org/x/tools/cmd/goimports
          npm install markdown-toc

      - name: Run Tests
        run: |
          go run build.go vet
          go run build.go test
          go run build.go gfmrun docs/v2/manual.md
          go run build.go toc docs/v2/manual.md